# Generated by Django 5.2.7 on 2025-10-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcript',
            name='bullets',
        ),
        migrations.AddField(
            model_name='transcript',
            name='channel_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transcript',
            name='duration',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transcript',
            name='guest_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transcript',
            name='highlights',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transcript',
            name='host_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transcript',
            name='key_moments',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transcript',
            name='publish_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transcript',
            name='quotes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transcript',
            name='sentiment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transcript',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transcript',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='transcript',
            name='topics',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transcript',
            name='video_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
