# Generated by Django 5.2.7 on 2025-10-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0002_remove_transcript_bullets_transcript_channel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcript',
            name='channel_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='guest_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='host_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
