# Generated by Django 5.2.7 on 2025-10-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verify_token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
